ⓄⓊⓉ← {ⓁⒻⓉ} ∆F ⓇⒼⓉ; ⎕TRAP 
⍝ ∆F: [Add doc here]
  ⎕TRAP← 0 'C' '⎕SIGNAL ⊂⎕DMX.(''EM'' ''EN'' ''Message'' ,⍥⊂¨(''∆F '',EM) EN Message)'
  
⍝ ⓁⒻⓉ:  mode debug escCh extLib
⍝       mode: 1 (std mode: default), 0 (code mode), ¯1 (list mode), ¯2 (table mode)
⍝           std:   format and return the object generated.
⍝           code:  create a dfn to format and generate an object; useful when
⍝                  the function is going to be called repeatedly on different data.
⍝           list:  format and return the object generated, boxing each field of the object 
⍝                  separately left-to-right, using dfn ¨disp¨.
⍝           table: format and return the object generated, boxing each field of the object 
⍝                  separately in a "table", one field above the other, using dfns ¨disp¨.
⍝       debug: If 1, carriage returns (`⋄) are replaced by a visible rep: ␍
⍝                In addition, the intended executable is printed before execution.
⍝       escCh: the "escape" char (default '`'). If a number is passed, rather than a char,
⍝              the default is assumed. (Useful when setting extLib as well)
⍝       extLib: 
⍝          ∘ If 1 (default), we use a namespace (library) ⍙F to hold key ∆F utilities
⍝            referenced in the code generated by The APL fn, ∆F. ∆F generates ⍙F utilities.
⍝            Generates a more compact code string than if extLib=0.
⍝          ∘ If 0, the utilities are included in the code created by the associated 
⍝            C routine called here. Any resulting dfn (mode 0) will be self-contained.
  :If 900⌶0
        ⓁⒻⓉ← 1    0     '`'   1         
  :ElseIf 0=≢ⓁⒻⓉ
       ⓄⓊⓉ← 1 0⍴⍬ 
       :Return 
  :Elseif 'help'≡⎕C ⓁⒻⓉ
       ⓄⓊⓉ← { ⎕ML←1 ⋄ ⍬⊣⎕ED⍠ 'ReadOnly' 1⊢'help'⊣help←↑'^\h*⍝H(.*)' ⎕S '\1'⊢⎕NR ⊃⍵ } ⎕XSI 
       :Return  
  :Else 
        ⓁⒻⓉ← 4↑ⓁⒻⓉ, 1    0     '`'   1↑⍨ ¯4+ ≢ⓁⒻⓉ
  :EndIf 

  ⓄⓊⓉ← (⊃⎕RSI)⍎ ⓁⒻⓉ {   
      ⎕IO ⎕ML←0 1 
    ⍝ options and arguments to ∆F 
      badEscE← 'DOMAIN ERROR: escape char not unicode scalar!' 11
      mode debug escCh extLib ← ⍺
      escCh← {0=⊃0⍴⍵: '`' ⋄ ⍵ }escCh 
  ×80| ⎕DR escCh: ⎕SIGNAL/ badEscE
  1≠ ≢escCh:      ⎕SIGNAL/ badEscE

    CheckLib← ⎕SE.{
      ⍵=0: ⍬ ⋄ 9=⎕NC '⍙F': ⍬
        _← '⍙F' ⎕NS ⍬
  ⍝  Define ∆F utilities-- for use if extLib=1 (default).
  ⍝  Merge all the elements to the right, adjusting for height, without adding blank columns.
      ⍙F.M← {⎕ML←1 ⋄⍺←⊢⋄ ⊃,/((⌈/≢¨)↑¨⊢)⎕FMT¨⍺⍵}
  ⍝  (%) Center field ⍺ above field ⍵. If ⍺ is omitted, a single-line field is assumed.
      ⍙F.A← {⎕ML←1 ⋄⍺←⍬⋄⊃⍪/(⌈2÷⍨w-m)⌽¨f↑⍤1⍨¨m←⌈/w←⊃∘⌽⍤⍴¨f←⎕FMT¨⍺⍵}
  ⍝  ($) Box item ⍵ 
      ⍙F.B←{⎕ML←1 ⋄1∘⎕SE.Dyalog.Utils.disp ,⍣(⊃0=⍴⍴⍵)⊢⍵}
  ⍝  (Modes ¯1 and ¯3) Displaying the entire formatted result
      ⍙F.D← ⎕SE.Dyalog.Utils.disp
        ⍬
    }  
    _← CheckLib extLib  

    ⍝ int fs_format(INT4 opts[4], CHAR4 fString[], INT4 fStringLen, CHAR4 outBuf[], INT4 *outPLen)
    ⍝ opts: (see below)
    ⍝ fString: the format string
    ⍝ outBuf:  the output buffer (on input: the output buffer size needed)
    ⍝ outPLen: the output buffer size (on input: the same number as for outBuf)
    ⍝ Returns:  rc outBuf outPLen
    ⍝   rc:     0 (ok), >0 (APL signal code [error]), ¯1: (outBuf too small)
    ⍝   outBuf: the actual output buffer in 4-byte chars. Chars beyond outPLen are junk.
    ⍝   outPLen: the actual length (in 4-byte chars) of code output
        _← debug ⎕SE.{ 
          _← ⎕EX⍣⍺⊢⍵  ⍝⍝⍝ Only TEST mode 
          ⍵ ⎕NA⍣(⊃0=⎕NC ⍵)⊢ 'I4 ∆F.dylib|fs_format  <I4[4] <C4[] I4  >C4[] =I4' 
        }'∆F_C'            ⍝ 'rc              opts   fStr  ≢fStr res   lenRes
 
        opts4← mode debug (⎕UCS escCh) extLib 
        outLen← (extLib⊃ 1024 512)⌈ (extLib⊃10 5)× ≢fStr← ⊃,⊆⍵ 
 
        DOut← {debug=1: ⊢⎕←⍵ ⋄ ⍵}
        rc res lenRes← ⎕SE.∆F_C opts4 fStr (≢fStr) outLen outLen 

     0= rc:    DOut lenRes↑ res 
    ¯1= rc:     911 ⎕SIGNAL⍨  {
        'DOMAIN ERROR: Formatting buffer not big enough (buf size: ',(⍕⍵),' elements)'
    }outLen
               rc  ⎕SIGNAL⍨ (⎕EM rc),': ', lenRes↑res 
  } ⊃ⓇⒼⓉ← ,⊆ⓇⒼⓉ

⍝H <<< NO HELP AVAILABLE >>>

